#---------------------------------#
#      general configuration      #
#---------------------------------#

version: '{build}'

branches:
  only:
    - develop
    - master

skip_commits:
  files:
    - '**/*.md'

#---------------------------------#
#    environment configuration    #
#---------------------------------#

image: Visual Studio 2017


matrix:
  fast_finish: true     # set this flag to immediately finish build once one of the jobs fails.

environment:
  MDNSWINDOWS_VERSION: v1.0.0

install:
  - ps: |-
      mkdir mdns_install
      (new-object net.webclient).DownloadFile('https://github.com/ETCLabs/mDNSWindows/releases/download/$Env:MDNSWINDOWS_VERSION/mDNSWindows_Win32.zip' 'mdns_install\x86.zip')
      (new-object net.webclient).DownloadFile('https://github.com/ETCLabs/mDNSWindows/releases/download/$Env:MDNSWINDOWS_VERSION/mDNSWindows_x64.zip' 'mdns_install\x64.zip')

for:
-
  matrix:
    only:
      - platform: x86
  
  environment:
    CMAKE_GENERATOR: Visual Studio 15 2017 Win64
    CMAKE_INSTALL: install_x86
    QTDIR: C:\Qt\5.9.7\msvc2015

  artifacts:
    - path: tools/install/windows/bin/Release/RDMnetSetup_x86.msi
      name: RDMnet 32-bit installer

-
  matrix:
    only:
      - platform: x64

  environment:
    CMAKE_GENERATOR: Visual Studio 15 2017
    CMAKE_INSTALL: install_x64
    QTDIR: C:\Qt\5.9.7\msvc2017_64

  artifacts:
    - path: tools/install/windows/bin/Release/RDMnetSetup_x64.msi
      name: RDMnet 64-bit installer

#---------------------------------#
#       build configuration       #
#---------------------------------#

platform:
  - x86
  - x64

configuration: Release

before_build:
  - cmd: |-
      git clone -b %APPVEYOR_REPO_BRANCH% https://github.com/ETCLabs/lwpa ../lwpa
      git clone -b %APPVEYOR_REPO_BRANCH% https://github.com/ETCLabs/RDM ../RDM
      mkdir build
      cd build
      cmake --version
      cmake -G "%CMAKE_GENERATOR%" -DCMAKE_INSTALL_PREFIX=%CMAKE_INSTALL% -DRDMNET_MOCK_DISCOVERY=ON ..

build:
  parallel: true            # enable MSBuild parallel builds
  project: build\RDMnet.sln # path to Visual Studio solution or project

  # MSBuild verbosity level
  verbosity: minimal

after_build:


#---------------------------------#
#       tests configuration       #
#---------------------------------#

test_script:
  - cmd: tests\unit\%configuration%\test_rdmnet_lib.exe

# Custom build configuration for 'develop' branch: Create a versioned build.
# for:
# -
#   branches:
#     only:
#       - develop
#   
#   before_build:
#     - cmd: |-
#         git clone -b %APPVEYOR_REPO_BRANCH% https://github.com/ETCLabs/lwpa ../lwpa
#         git clone -b %APPVEYOR_REPO_BRANCH% https://github.com/ETCLabs/RDM ../RDM
#         mkdir build
#         cd build
#         cmake --version
#         cmake -G "Visual Studio 15 2017 Win64" -DQTDIR=C:\Qt\5.9.7\msvc2017_64 -DRDMNET_MOCK_DISCOVERY=ON -DRDMNET_CREATE_VERSIONED_BUILD=ON -DRDMNET_VERSION_BUILD=%APPVEYOR_BUILD_NUMBER% ..
# 
# -
#   branches:
#     only:
#       - master
# 
#   environment:
#     access_token:
#       secure: D2tJBo+pb7fiu19yt3FYK5QSqT9bnMdlBHEIWutil33+rKjt1cP5nnB0m1XMkTsM
# 
#   before_build:
#     - cmd: |-
#         git clone -b %APPVEYOR_REPO_BRANCH% https://github.com/ETCLabs/lwpa ../lwpa
#         git clone -b %APPVEYOR_REPO_BRANCH% https://github.com/ETCLabs/RDM ../RDM
#         mkdir build
#         cd build
#         cmake --version
#         cmake -G "Visual Studio 15 2017 Win64" -DQTDIR=C:\Qt\5.9.7\msvc2017_64 -DRDMNET_MOCK_DISCOVERY=ON -DRDMNET_CREATE_VERSIONED_BUILD=ON -DRDMNET_VERSION_BUILD=%APPVEYOR_BUILD_NUMBER% ..
# 
#   on_success:
#     - git config --global credential.helper store
#     - ps: Add-Content "$HOME\.git-credentials" "https://$($env:access_token):x-oauth-basic@github.com`n"
#     - git config --global user.email "appveyor@appveyor.com"
#     - git config --global user.name "AppVeyor CI"
#     - git add include/rdmnet/version.h
#     - git commit -m "Bump version header from AppVeyor CI. Build number %APPVEYOR_BUILD_NUMBER%"
#     - git push origin master
