#---------------------------------#
#      general configuration      #
#---------------------------------#

version: '{build}'

branches:
  only:
    - develop
    - master
    # Temporary add for installer testing
    - build-installer

skip_commits:
  files:
    - '**/*.md'

#---------------------------------#
#    environment configuration    #
#---------------------------------#

image: Visual Studio 2017


matrix:
  fast_finish: true     # set this flag to immediately finish build once one of the jobs fails.

environment:
  MDNSWINDOWS_VERSION: v1.1.0
  
  matrix:
    - VERSIONED_BUILD: 'no'
    - VERSIONED_BUILD: 'yes'

for:
  -
    matrix:
      only:
        - platform: x86
    
    environment:
      CMAKE_GENERATOR: Visual Studio 15 2017
      CMAKE_INSTALL: install_x86
      QTDIR: C:\Qt\5.9.7\msvc2015
      INSTALLER_PROJECT: tools\install\windows\RDMnetInstall_x86.wixproj
      INSTALLER_PROJECT_PLATFORM: x86
      INSTALLER_ARTIFACT: tools\install\windows\bin\Release\RDMnetSetup_x86.msi

    install:
      - ps: (new-object net.webclient).DownloadFile("https://github.com/ETCLabs/mDNSWindows/releases/download/$Env:MDNSWINDOWS_VERSION/mDNSWindows_Win32.zip", "$Env:APPVEYOR_BUILD_FOLDER\mDNSWindows_Win32.zip")
      - cmd: 7z x mDNSWindows_Win32.zip -omdns_install -y -r

    artifacts:
      - path: RDMnetSetup_x86.msi
        name: RDMnet 32-bit installer

  -
    matrix:
      only:
        - platform: x64

    environment:
      CMAKE_GENERATOR: Visual Studio 15 2017 Win64
      CMAKE_INSTALL: install_x64
      QTDIR: C:\Qt\5.9.7\msvc2017_64
      INSTALLER_PROJECT: tools\install\windows\RDMnetInstall_x64.wixproj
      INSTALLER_PROJECT_PLATFORM: x64
      INSTALLER_ARTIFACT: tools\install\windows\bin\Release\RDMnetSetup_x64.msi

    install:
      - ps: (new-object net.webclient).DownloadFile("https://github.com/ETCLabs/mDNSWindows/releases/download/$Env:MDNSWINDOWS_VERSION/mDNSWindows_x64.zip", "$Env:APPVEYOR_BUILD_FOLDER\mDNSWindows_x64.zip")
      - cmd: 7z x mDNSWindows_x64.zip -omdns_install -y -r

    artifacts:
      - path: RDMnetSetup_x64.msi
        name: RDMnet 64-bit installer
    
  -
    matrix:
      only:
        - VERSIONED_BUILD: 'yes'

    only_commits:
      message: /<versioned-build>/

    environment:
      CMAKE_EXTRA_ARGS: -DRDMNET_MOCK_DISCOVERY=OFF -DMDNSWINDOWS_INSTALL_LOC=../mdns_install

    after_build:
      - cmd: |-
          cmake -P cmake_install.cmake
          msbuild /m /p:Platform=%INSTALLER_PROJECT_PLATFORM% ..\%INSTALLER_PROJECT%
          copy ..\%INSTALLER_ARTIFACT% ..

  -
    matrix:
      only:
        - VERSIONED_BUILD: 'no'

    environment:
      CMAKE_EXTRA_ARGS: -DRDMNET_MOCK_DISCOVERY=ON

    test_script:
      - cmd: tests\unit\%configuration%\test_rdmnet_lib.exe

#---------------------------------#
#    common build configuration   #
#---------------------------------#

platform:
  - x86
  - x64

configuration: Release

before_build:
  # TODO change branches back to %APPVEYOR_REPO_BRANCH%
  - cmd: |-
      git clone -b develop https://github.com/ETCLabs/lwpa ../lwpa
      git clone -b develop https://github.com/ETCLabs/RDM ../RDM
      mkdir build
      cd build
      cmake --version
      cmake -G "%CMAKE_GENERATOR%" -DCMAKE_INSTALL_PREFIX=%CMAKE_INSTALL% %CMAKE_EXTRA_ARGS% ..

build:
  parallel: true            # enable MSBuild parallel builds
  project: build\RDMnet.sln # path to Visual Studio solution or project

  # MSBuild verbosity level
  verbosity: minimal
