# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- develop

pr:
- develop

jobs:
# Build and test RDMnet on Windows using CMake and Visual Studio 2017.
- job: windows_build
  displayName: 'Windows Build and Test'
  pool:
    vmImage: 'vs2017-win2016'
  strategy:
    matrix:
      Win32:
        CMAKE_GENERATOR: 'Visual Studio 15 2017'
      x64:
        CMAKE_GENERATOR: 'Visual Studio 15 2017 Win64'
  steps:
    - script: |
        git clone -b develop https://github.com/ETCLabs/lwpa ../lwpa 
        git clone -b develop https://github.com/ETCLabs/RDM ../RDM
        cd ..\lwpa
        git checkout 0aa3362
        cd ..\RDM
        git checkout dd850f2
        cd $(Build.SourcesDirectory)
        mkdir build
        cd build
        cmake --version
        cmake -G "%CMAKE_GENERATOR%" -DCMAKE_INSTALL_PREFIX=install -DRDMNET_BUILD_CONSOLE_EXAMPLES=ON -DRDMNET_MOCK_DISCOVERY=ON ..
        cmake --build . --config Release
        cmake -P cmake_install.cmake
      displayName: 'RDMnet Windows build'
    - script: ctest -C Release
      displayName: 'RDMnet Windows test'
      env:
        CTEST_OUTPUT_ON_FAILURE: '1'
    - task: PublishPipelineArtifact@0
      inputs:
        artifactName: 'rdmnet_built_artifacts'
        targetPath: 'build/install'

